In [1]:
from f1score import *

In [2]:
PREFIX = '400'

true_dict = get_true_annotation('../seareale/config.yaml')
pred_dict = get_pred_annotation(f'../seareale/answersheet_4_03_seareale_{PREFIX}.json')

_, f1, con_mat = AGC2021_f1score(true_dict, pred_dict)
_, f1_zero, con_mat_zero  = AGC2021_f1score(true_dict, pred_dict, include_zero=True)

_, _ = show_confMat(con_mat, PREFIX)
_ = plot_f1score(f1, PREFIX)
_, _ = show_confMat(con_mat_zero, PREFIX+'_zero')
_ = plot_f1score(f1_zero, PREFIX+'_zero')



>> Macro F1 score 
------------------------
paper     : 0.6510
paperpack : 0.8583
can       : 1.0000
pet       : 1.0000
vinyl     : 0.8077
------------------------
TOTAL     : 0.8634

>> Macro F1 score - include zero
------------------------
paper     : 0.6497
paperpack : 0.8478
can       : 1.0000
pet       : 1.0000
vinyl     : 0.7957
------------------------
TOTAL     : 0.8587


In [3]:
con_mat

NameError: name 'con_mat' is not defined

In [3]:
con_mat[3]

(array([[113.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   3.]]),
 (array([1, 2, 3, 4]), array([1, 2, 3, 4])))

In [4]:
con_mat[2]

(array([[195.,   1.,   0.],
        [  0.,  12.,   1.],
        [  0.,   1.,   1.]]),
 (array([1, 2, 3]), array([1, 2, 3])))

In [5]:
np.sum(con_mat[2][0][0,:]) - np.sum(con_mat[2][0][0,0])

1.0

In [6]:
np.sum(con_mat[2][0][:,0]) - np.sum(con_mat[2][0][0,0])

0.0